### ISSUE TITLE
document files

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#101]
Add files to the list of things that `crate::usage` knows how to document, and document the config file's location.

Documenting its contents can wait :)

**Comment by savchenko** [comment]
Stashing all the way into [v0.7.0](https://github.com/taskchampion/taskchampion/milestone/4) unless someone picks this up earlier.

**Comment by djmitche** [comment]
I think this is pretty much the only file location required, and it's documented at https://taskchampion.github.io/taskchampion/config-file.html -- so I don't think this needs to be done.
