### ISSUE TITLE
Limit modifications allowed in the `add` command

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#105]
`task add -foo` doesn't make much sense, so we should flag that as an error.  Similar, `task add` (without a description) should be an error.

**Comment by savchenko** [comment]
> task add -foo doesn't make much sense

Looks dubious, but an error?

`ta add -Don't write so that you can be understood; write so that you can't be misunderstood `

**Comment by savchenko** [comment]
All clear. Opportunistically added to v0.4.0 as checking if `add` parameter starts with <kbd>-</kbd> doesn't sound too complicated. Please feel free to amend if this isn't the case.

**Comment by djmitche** [comment]
On reflection, let's not do this.  If we get to the point of having somthing like a context (c.f. #163) that affects new tasks, it may make sense to use `-tag` to remove a tag that context would otherwise add.  Until then `ta add foo -bar` will just add a new task with no tags.
