### ISSUE TITLE
Improve efficiency of filtering by a mix of working set IDs and partial UUIDs

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#108]
See the "NOTE" in `cli/src/invocation/filter.rs`.

**Comment by djmitche** [comment]
The refactor in #121 is going to make this harder to spot, but it will still be an issue.  #123 is probably necessary to fix it.

**Comment by savchenko** [comment]
> See the "NOTE" in cli/src/invocation/filter.rs.

There is no note in the `cli/src/invocation/filter.rs`. 

```
~/code/taskchampion/cli/src/invocation (main)
 ◊ grep -i note *.rs
 ◊ 
 ```

Could you provide more context as to where this belongs?

**Comment by djmitche** [comment]
The note was [here](https://github.com/taskchampion/taskchampion/commit/fc977a0fe65884edf40de829e1e218eaa39763d0#diff-d6119b2d9dfa2fc010a4aa8c8e33b0753b27e15a8353c25dff4f1ea5b3065ae1L53), from #121.  And indeed, that PR did not fix it.  However, #145 did address this issue -- the working set is only read from storage once, and re-used as necessary.
