### ISSUE TITLE
Test cli + sync-server in a grand old integration test

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#128]
Let's put everything together in at least one integration test that runs a few replicas against a sync server.

This *might* require a `tests` directory at the Cargo workspace level.  If cargo doesn't support that, then just do it in a shell script!

**Comment by dbr** [comment]
> This _might_ require a `tests` directory at the Cargo workspace level. If cargo doesn't support that, then just do it in a shell script!

This should be doable by creating an additional crate at the top level, which can then have dependencies on `{path = "../sync-server"}` and `{path = "../taskchampion"}`, then spawn the server in a thread or something like that

**Comment by savchenko** [comment]
Adding to [v0.6.0](https://github.com/taskchampion/taskchampion/milestone/3) based mostly on how crowded earlier milestones are. Please ping this issue if you believe this must be done earlier.
