### ISSUE TITLE
Switch to a new data-storage layer

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#131]
Running the sync server without any arguments gives
```
Error: LMDB(Other(2))
```

which isn't that useful!

**Comment by djmitche** [comment]
Good news!  The `kv` crate, as of version 0.20.0, totally changed its backend DB and its API.  That's good news because it means we can avoid that particular crate and its attendant rustacean 0.x'ism.

The bad news is, it doesn't look like the alternatives are much better.
 * https://docs.rs/rkv/ is also 0.x and poorly documented.  Looking at the README in GitHub, it appears the LMDB backend crashes, and the "SafeMode" backend is in-memory only.  Lol.
 * https://docs.rs/lmdb/ appears to be abandoned
 * https://docs.rs/lmdb-rkv appears to be a fork of lmdb by Mozilla, also abandoned

https://docs.rs/sled/ doesn't look bad, and is actively maintained.  It's also 0.x though.  I wish crates.io had a way to search by version!

**Comment by djmitche** [comment]
> if reliability is your primary constraint, use SQLite. sled is beta.

OK :)

**Comment by dbr** [comment]
Started on this in #206

**Comment by savchenko** [comment]
@dbr , how much work is left? Is this a "few hours of work" or a few days?... Weeks?

**Comment by dbr** [comment]
Probably a few hours left - it's just a matter of implementing the last ~5 methods on [StorageTxn](https://github.com/taskchampion/taskchampion/blob/6a0bddab38ff7dc7f4540f22e8e2df4ca06ae04e/taskchampion/src/storage/mod.rs). Given how straight forward the rest have been so far (implement a method, a bunch of tests start passing, repeat) I can't imagine the remaining ones causing might trouble 🥳
