### ISSUE TITLE
Make a `task config` command to dump the configuration

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#138]
..including defaults.

**Comment by dbr** [comment]
Quite possibly relates to #164 to also set config options

**Comment by djmitche** [comment]
#164 is in the 0.4.0 milestone, so this should be as well.

**Comment by djmitche** [comment]
The question here is, do we want to dump the config file as-written (comments, etc.), or to regenerate that format from scratch.  The former is basically `cat $TASKCHAMPION_CONFIG`.  The advantage to the latter will show the defaults (mostly reports), but is quite a bit of code.  Is that worthwhile?

**Comment by savchenko** [comment]
> dump the config file as-written

Sounds like an easier option. I don't see much of a value in the 2nd option as defaults can be documented separately and in a more readable form.

**Comment by dbr** [comment]
Broader question would be, do we even need it show it via the CLI? Possibly just having an `ta config` arg which shows the path to the config would be enough? (then people can do `cat $(ta config path)` or whatever)

The option to show the values would be useful if either:

1. It only showed a validated form of the config - e.g if someone had `thingo = "..."` but it should be `thingy = "..."` then the option would not appear in the config (unless this causes it to error already? Haven't checked)
2. It shows all options so people can find/copy/tweak - I find "in line" documentation for such things much nicer than having to dig and find the relevant docs. However we should probably carefully avoid encouraging`ta config show > my_new_config.toml` as this makes the config much bulkier than it probably needs to be, and makes carefully changing default values harder
3. `ta config set thingo` has a mirrored `ta config get thingo` as a debugging tool for documentation etc, e.g "if sync isn't working check your remote URL is correct using `ta config get ...`

For now I'd probably vote for just the "show path to config" option, and maybe add more elaborate output of the config later if needed

**Comment by djmitche** [comment]
>     1. It only showed a validated form of the config - e.g if someone had `thingo = "..."` but it should be `thingy = "..."` then the option would not appear in the config (unless this causes it to error already? Haven't checked)

When the config is parsed, yes, this will be flagged as an error.

>     2. It shows all options so people can find/copy/tweak - I find "in line" documentation for such things much nicer than having to dig and find the relevant docs. However we should probably carefully avoid encouraging`ta config show > my_new_config.toml` as this makes the config much bulkier than it probably needs to be, and makes carefully changing default values harder

This is probably a good use-case, although we currently only have 5 top-level config values, so not that useful right now.  This might also be addressed with a checked-in file somewhere that we can link to as a "starter" config.  Let's do that when we need it.

>     3. `ta config set thingo` has a mirrored `ta config get thingo` as a debugging tool for documentation etc, e.g "if sync isn't working check your remote URL is correct using `ta config get ...`

Yeah, I've been about that, but kind of want to wait until we have more config options.

> For now I'd probably vote for just the "show path to config" option, and maybe add more elaborate output of the config later if needed

Sounds good.  `ta config path`.

**Comment by djmitche** [comment]
It'd be weird to use `-X` style flags for this part of the CLI.  And, since most commands don't modify anything, I don't think we need a special "no-op" command.

**Comment by dbr** [comment]
> make sense to have -t flags that tests config silently

Yep, but I think if an invalid config should cause any `ta` invocation to error, then we don't need a specific flag to validate the config - anything beyond `ta help` would error explaining why the config is invalid

In other words, if someone mangles their config then `ta add Test` etc etc will give a useful error, so no need for a specific "check config" option. If we then add a "show current config values" command in future, then that covers the "dump validated config" option too

**Comment by djmitche** [comment]
(Waiting on #228)
