### ISSUE TITLE
Generate mdbook documentation contents

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#140]
All the things in usage should go into the book, with a CI check to make sure the generation has been performed before a PR is merged.

This should include the allowed sort_by and columns for reports.

**Comment by savchenko** [comment]
Let's define a list of CI checks in https://github.com/taskchampion/taskchampion/discussions/219 before top comment becomes a victim of endless edits.

**Comment by djmitche** [comment]
I guess I'm not sure why a discussion is a better place for this..

And, this isn't a "test all the things in CI" issue.  It's specifically about using CI to ensure that documentation has been generated from the code.

**Comment by savchenko** [comment]
> I guess I'm not sure why a discussion is a better place for this..

I am failing at times to see why "discussions" are necessary at all... Still created one.

> And, this isn't a "test all the things in CI" issue. It's specifically about using CI to ensure that documentation has been generated from the code.

I have copied description straight from the https://github.com/taskchampion/taskchampion/discussions/160. Reverting.

Would you create a separate one for the "matrix"? As you have noted in https://github.com/taskchampion/taskchampion/discussions/219#discussioncomment-669827, it is the only one left. Which is actually quite impressive for an early-stage project.

**Comment by djmitche** [comment]
I'm pretty big into CI :)

#216 covers adding the matrix to test both against the MSRV and stable.
