### ISSUE TITLE
Fix dangling links in docs

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#149]
- https://djmitche.github.io/taskchampion/installation.html
- https://djmitche.github.io/taskchampion/usage.html
- https://djmitche.github.io/internals.html
- https://djmitche.github.io/plans.html

**Comment by savchenko** [comment]
Few 404s left:
- https://taskchampion.github.io/taskchampion/installation.html
- https://taskchampion.github.io/taskchampion/usage.html

**Comment by savchenko** [comment]
https://taskchampion.github.io/ returns 404 now. Let's re-open?..

**P.S.** What do you think about deploying to something like Netlify that renders previews for commits?
For example, if you have changed `foo.md` that affects `bar.html`, there would be a link to preview `bar.html` before the merge.

**Comment by dbr** [comment]
Did https://taskchampion.github.io/ work before? The root of the book is at
https://taskchampion.github.io/taskchampion/
..which I suspect was same as before - however pages definitely are missing (which is weird as if I run mdbook locally it's fine)

**Comment by savchenko** [comment]
> Did https://taskchampion.github.io/ work before

Yes, there were only two 404s left, as mentioned in https://github.com/taskchampion/taskchampion/issues/149#issuecomment-827515191

**Comment by dbr** [comment]
Yeh, a strangeness of GH Pages is the no-prefix `https://taskchampion.github.io/` needs to come from a repo named `taskchampion.github.io`

Might be easier just to create `taskchampion.github.io` with a simple "logo + link to docs" type placeholder (or a temporary redirect?) than working out how to publish the docs in this repo to a separate repo?

**Comment by djmitche** [comment]
I like the redirect idea.  I don't think we need to worry too much about this until we have a more usable app.  The docs are linked from the README right now, at the right URL.

Netlify's not a bad idea, if it's free, but I'm not sure how to set that up.

At any rate, this is, indeed, finished :)

**Comment by savchenko** [comment]
I might be missing something here, but opening the 1st page of documentation, user is presented with the sentence:

> See Usage for more detailed information on using TaskChampion.

The word "usage" is hyperlinked to https://taskchampion.github.io/taskchampion/usage.html which is 404.

Next, there is a sentence:

> Once you've installed TaskChampion, your interface will be via the task command. Start by adding a task:

Phrase "installed TaskChampion" is linked to https://taskchampion.github.io/taskchampion/installation.html which is 404 as well.

**Comment by djmitche** [comment]
It looks like the automatic deployment is broken -- #227.
