### ISSUE TITLE
CLI command to set config options

### ISSUE THREAD

**Issue by dbr** [taskchampion/taskchampion#164]
As discussed in https://github.com/djmitche/taskchampion/discussions/152

It would help with writing good user-guides to have a CLI which can set config options, maybe something like

    task config set sync-server-origin http://example.com

or maybe more locally specific

    task sync set-url http://example.com

or something along those lines.

Justification being that "run this command to set the server" is a lot friendly than "edit the config at [platform dependent location], then in this section, add the line [...etc]"

Git is a good reference for this - e.g the commands for setting name/email are presented in error messages from git itself, remote URL's are presented by hosting services like Github.

**Comment by djmitche** [comment]
This seems quite common.  I think we'd need to pick another config language, though -- I don't think the YAML parser preserves enough state (comments, whitespace) to "edit" a file without losing the user's formatting.  I think TOML can do this?  At least, `cargo add` edited my `Cargo.toml` without losing comments..  And TOML seems to be getting more popular as a config format.

**Comment by dbr** [comment]
I'm in favour of using something which isn't YAML (popular but *giant* spec leading to things like [this website to help people with how to format a multi-line string](https://yaml-multiline.info/), among many other issues)

TOML would be my vote, although for how widely use it is I found the main `toml` crate surprisingly under-developed - I don't think it [currently supports preserving comments](https://github.com/alexcrichton/toml-rs/issues/83), and I've run in to other things like it being [sensitive to the order fields are defined](https://github.com/alexcrichton/toml-rs/issues/336). `cargo-edit` seems to use [this toml_edit](https://github.com/ordian/toml_edit) crate instead

I have also looked into [ron](https://github.com/ron-rs/ron) which seems interesting, as is [hcl](https://github.com/hashicorp/hcl) - although the former is fairly Rust-only, and the latter hasn't really caught on (and now I think about it, I'm not sure I found a Rust implementation of it.. so.. probably not too useful a suggestion!). There is also https://github.com/google/json5format which is JSON with support for preserving comments and some other changes, but seems quite early stages

Possibly `toml_edit` with the hope we can switch to the main `toml` crate someday when https://github.com/alexcrichton/toml-rs/issues/83 gets more attention?

**Comment by savchenko** [comment]
TOML sounds like a good balance. Given how central configuration is, do you think this can be added as early as in [v0.4.0](https://github.com/taskchampion/taskchampion/milestone/1)?

**Comment by djmitche** [comment]
Yes, that makes sense.
