### ISSUE TITLE
Move to a dedicated GitHub org

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#174]
This probably isn't necessary just yet, but soon we should move to a dedicated org.  Among other things, that allows "teams" and separates me from the project administration.  What milestone should we pin this to?

**Comment by dbr** [comment]
This is a good idea; and better to do now before there is much linking to the current location

**Comment by djmitche** [comment]
Good point!

**Comment by djmitche** [comment]
Well, that was easy.
