### ISSUE TITLE
Do not modify all tasks by default; require `*` for that

### ISSUE THREAD

**Issue by dbr** [taskchampion/taskchampion#177]
As per https://github.com/djmitche/taskchampion/discussions/153

`task 1 start` marks one task as active. Good.

Expected behaviour: `task start 1` should be equivalent

Current (v0.3) behavior: it finds all tasks matching empty filter, then modifies them with description 1 - essentially clobbering the description of all tasks with `"1"`

**Comment by djmitche** [comment]
#209 is a similar example of a task list being missed, and the assumption of a command applying to all tasks.  With similarly disastrous results.  #213 as well!  #179 addresses adding some messaging around this, but #213 has a nice idea of not allowing the "empty means all" filter, but requiring `*` for that case.

So, `ta done` does not mark all tasks as done; users must write `ta * done`.

The exception to this is reports, where an empty specification implies all tasks (reduced by any named or implicit filters).

**Comment by dbr** [comment]
`ta * done` will glob to `ta [all files in current dir] done in most shells and would need escaped or quoted to avoid that

Would `ta all done` be possible without being ambiguous or otherwise problematic?

**Comment by djmitche** [comment]
(answered in the PR)
