### ISSUE TITLE
Confirmation prompts

### ISSUE THREAD

**Issue by dbr** [taskchampion/taskchampion#179]
There are some batch operations where a confirmation may be helpful, e.g `task start` may want to prompt before marking every task as active

If undo (#92 ) is implemented, some of these could potentially be removed, and instead the output just inform the user that undo exists, something along the lines of "Note: Marking 1120 tasks as active - if this was not intended, run 'task undo' immediately to reverse this operation"

**Comment by savchenko** [comment]
While poking around https://github.com/taskchampion/taskchampion/issues/137, I have tried to show tasks that are done:
```
$ ta done
modified task 9590b11f-4cf9-4f77-879d-f5879c05c76c
modified task d864f740-cf2b-4a09-b256-60a0386fb29b
modified task edfce578-24ef-4961-8490-b872374f1a42
modified task 91678ad0-929d-4aff-97be-620758af6758
```
...Now I'm thinking of https://github.com/taskchampion/taskchampion/issues/92 :) Perhaps if no argument is provided TaskChampion should assume that no task is be modified?

Example:
```sh
# Safe action by default, potentially destructive requires an explicit direction.
$ ta * mod done # sets all tasks to "done"
$ ta * done # shows all tasks that are done
```
