### ISSUE TITLE
TaskChampion identity design

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#207]
Future of task management needs a strong identity.

# Key points

Play on the completed task and champion's medal.

> snip!

# iOS icon

Easily recognizable either with or without the ribbon. 

> snip!
> snip!

# Alternative icon

Square or rounded... It is still TaskChampion.

> snip!

---

All work done in vector and can be exported in an arbitrary resolution.

**Comment by savchenko** [comment]
I have created dummy repository to test if it can be used, for example, as the GitHub org. icon: https://github.com/taskchampion-graphics

Appears to work in both light and dark modes.

**Comment by djmitche** [comment]
(per chat discussion) I think the "V" of the ribbon is going to be a critical part of the icon, so it'd be nice to see that still included in the various minimized versions.
