### ISSUE TITLE
Modification logic

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#209]
## Issue

In TaskWarrior, executing `task edit 1`, opens `$EDITOR` where task №1 can be edited manually. In TC:
```
ta add Sort-out TC repository
added task 91678ad0-929d-4aff-97be-620758af6758
 ~
 ◊ ta
 Id Description            Active Tags 
 1  Sort-out TC repository             Here
 ~
 ◊ ta modify 1
modified task 91678ad0-929d-4aff-97be-620758af6758
 ~
 ◊ ta
 Id Description Active Tags 
 1  1                       
```
Above, I have added task, tried to modify it and it somehow changed its description to "1"... Let's try again:
```
◊ ta 1 modify Figure out how to use TC
modified task 91678ad0-929d-4aff-97be-620758af6758
 ~
 ◊ ta
 Id Description              Active Tags 
 1  Figure out how to use TC 
```
Good.

## Questions

1. Would it make sense to change "modify" to "edit"? 2 bytes shorter, easier to type.
2. If the description is empty, wouldn't it make sense to do nothing and warn user that no changes were made?

**Comment by djmitche** [comment]
I was planning to keep TW's edit/modify distinction (open an editor / make modifications based on CLI)

I think what you're seeing is that `ta modify 1` is parsing as a modification of all tasks to have description "1", so it's a parsing error.  That should be parsed as a modification of task 1 with no changes (which should probably generate a warning).

**Comment by savchenko** [comment]
>  That should be parsed as a modification of task 1 with no changes (which should probably generate a warning).

Maybe a notice? "Requested an edit, but no changes provided. Doing nothing." :)

**Comment by dbr** [comment]
I think this is very similar issue to #177 where `ta start 1` currently modifies all tasks to have the description of `1`

> Maybe a notice? "Requested an edit, but no changes provided. Doing nothing." :)

..and even better, a suggestion of how to use the command usefully - e.g `You can do [...] by running ta 1 modify [...]`

**Comment by djmitche** [comment]
Yeah, let's merge these together.

**Comment by savchenko** [comment]
_(note for a future: this is tracked in https://github.com/taskchampion/taskchampion/issues/97)_
