### ISSUE TITLE
Safer command-line logic

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#213]
While poking around https://github.com/taskchampion/taskchampion/issues/137, I have tried to show tasks that are done:
```
$ ta done
modified task 9590b11f-4cf9-4f77-879d-f5879c05c76c
modified task d864f740-cf2b-4a09-b256-60a0386fb29b
modified task edfce578-24ef-4961-8490-b872374f1a42
modified task 91678ad0-929d-4aff-97be-620758af6758
```
...Now I'm thinking of https://github.com/taskchampion/taskchampion/issues/92 :) Perhaps if no argument is provided TaskChampion should assume that no task is be modified?

Example:
```sh
# Safe action by default, potentially destructive requires an explicit direction.
$ ta * mod done # sets all tasks to "done"
$ ta * done # shows all tasks that are done
```

**Comment by dbr** [comment]
Similar to #177 - there's a few places where the CLI is a bit overly eager to bulk-change tasks.

#179 will also help with this

**Comment by savchenko** [comment]
True. Could you post content of your https://github.com/taskchampion/taskchampion/issues/177 under the https://github.com/taskchampion/taskchampion/issues/179? I will do the same and then we can close the extraneous issues.
