### ISSUE TITLE
Minimum supported Rust version

### ISSUE THREAD

**Issue by dbr** [taskchampion/taskchampion#216]
#212 mentions targeting only stable Rust, however in terms of making it easier to package on Linux distros, it might make sense to ensure we can build TC with a specific Rust version (tested via CI)

https://repology.org/project/rust/badges

Based on that I'd say 1.47 because:

- Debian Testing is on 1.48
- CentOS is on 1.47
- Ubuntu 16.04 through 20.10 is on 1.47
- Alpine Linux 3.13 is also on 1.47 (may be useful for docker container for sync-server)
- The rest I'm either not familiar with or are on 1.51

I don't think there's too much we'd miss in Rust 1.48-1.51:

- https://blog.rust-lang.org/2020/11/19/Rust-1.48.html
- https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html
- https://blog.rust-lang.org/2021/02/11/Rust-1.50.0.html
- https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html

Major changes in those versions are const-generics (not too useful for TC) and nicer linking in rustdocs (we can still this as we would only be maintaining support for a specific version of Rust, not necessarily actually using it for builds). Main trouble will likely be dependencies relying on newly stabilized API's

**Comment by djmitche** [comment]
This makes a lot of sense.  I think https://github.com/rust-lang/rfcs/blob/master/text/2495-min-rust-version.md suggests a way to publish this, and the github-actions "matrix" should allow us to test on both our MSRV and stable.  An added bonus there is that if a new stable Rust starts causing CI errors, we can see that in the check results (all MSRV tests pass, and some stable tests fail) and continue to merge PRs while we fix the errors.

**Comment by savchenko** [comment]
_(pending resolution in https://github.com/taskchampion/taskchampion/discussions/219)_

**Comment by djmitche** [comment]
I think we can resolve this right here :)

**Comment by savchenko** [comment]
_(removed TBD, added to v0.6.0)_

**Comment by djmitche** [comment]
The MSRV RFC isn't implemented yet, so we'll just include this in the README.  https://github.com/rust-lang/rust/issues/65262
