### ISSUE TITLE
Sort tasks by ID as the default output

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#232]
Not sure what is the current default sorting method, but it does not appear to be either "latest first" or "oldest first". 
Let's sort by time created as the default?

**Comment by djmitche** [comment]
By ID or by created time?

**Comment by savchenko** [comment]
Isn't _ID_ a "virtual" property that gets re-created anyway?
```
1
2 <-- done
3 <-- done
4
5

Becomes:

1
2
3
```

Otherwise, this can get ugly rather quickly:

```
1  This task was created first
8  Tasks 2-7 were done
13 And tasks 9-12 were done
25 ...as well as 14-24
```

**Comment by savchenko** [comment]
>  Still, it's easy to switch it to id -- that's just a difference in the default report

Then let's do it and get back to this issue closer to the v1.0?

_(Ping https://github.com/taskchampion/taskchampion/issues/87, shuffling this under [Future](https://github.com/taskchampion/taskchampion/milestone/8))_
