### ISSUE TITLE
Use ID instead of UUID in the shell output

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#233]
```
$ ta
 Id Description                       Active Tags 
 1  Do things
$ ta 1 done
 modified task 11a0d3v3-c40c-4b15-83a7-bh83c13fec64                 
```
Perhaps `modified task #1` is more humane?

**Comment by djmitche** [comment]
Sounds good to me!

**Comment by dbr** [comment]
Possibly the output could include more than just the ID, e.g  `modified task #1 ("Do thing and [...]")`. Would help users (especially, me) from noticing if they typed the wrong ID, or a filter which accidentally catches the wrong tasks
