### ISSUE TITLE
Reduce default verbosity

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#240]
Building from cea5ae8:

```
$ ta done 22
modified task 05550979-63a6-498d-87b4-2bb89404bebd
modified task 9034ba03-6355-468e-b3f0-9dd2d3d87c3c
modified task 9590b11f-4cf9-4f77-879d-f5879c05c76c
modified task 91678ad0-929d-4aff-97be-620758af6758
modified task 21956370-2c0d-4249-99c8-6104b6d839c3
modified task a57b53be-4f82-42e9-aceb-6e3a8e7ca3b8
modified task 87df9f11-0364-4e2b-b6e0-6b448529271b
...
```

Perhaps let's not print the whole chain of modified states? Some users might have 100+ tasks.

**Comment by dbr** [comment]
In that example, I think it has actually modified every task that is listed - `ta done 22` currently updates tasks which match empty filter, and replaces the description with `22` - which is issue #177

`ta 22 done` would only output a single "modified task" - ideally it would say something more useful (#233)

**Comment by djmitche** [comment]
Yep, I think this is handled in those two issues (one of which has been waiting for review for a few weeks)

**Comment by dbr** [comment]
> one of which has been waiting for review for a few weeks

..oops 🏃
