### ISSUE TITLE
match values of `status` to those in TaskWarrior

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#318]
TW uses `pending`, `completed', etc.  TC is using single-letter abbreviations.

**Comment by dbr** [comment]
At what level does this need to change for how TW's usage?

E.g there is already one letter mappings for `Status` API calls in https://github.com/taskchampion/taskchampion/blob/acd4aefc17a1b8615ef75e52c02f26665a46cd07/taskchampion/src/task/status.rs

**Comment by djmitche** [comment]
Yeah, we need to switch from P/C/D to `pending`, `completed`, and `deleted`.  It just needs a few lines of diff in the file you linked to.

**Comment by dbr** [comment]
Ohh this makes sense now - I mentally swapped TW and TC when reading the initial comment :roll_eyes:
