### ISSUE TITLE
Reserve some UUIDs for non-task data

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#335]
We may, at some point, want to support storing non-task data in the taskdb.  For example, it may make sense to store urgency information or UDA definitions.

To make room to do so later, let's reserve some subset of UUIDs, disallowing their use as task identifiers.

**Comment by dbr** [comment]
I don't understand how reserving UUID's would work - aren't they just random generated identifiers..?

**Comment by djmitche** [comment]
I think there's some "classes" of identifiers, like v4.  I'm not sure though -- needs some research :)

**Comment by dbr** [comment]
Ahh, right - there is various versions of the UUID spec, https://en.wikipedia.org/wiki/Universally_unique_identifier#Versions although I'm not sure it makes sense to use anything but v4 - and given there is "a total of 2122, or 5.3×1036 (5.3 [undecillion](https://en.wikipedia.org/wiki/Names_of_large_numbers)) possible version-4 variant-1 UUIDs", it seems odd to reserve any kind of subset of them (I guess you could do something like reserving `0*-0*-0*-0*-0*`, then generate them by making a random one and mangling it by setting the relevant bytes to 0x00)

..but, if the goal is to store non-task data, it seems like it might end up confusing to store this as special tasks accessed via the taskdb (e.g if something like "task urgency multiplier" info is stored as a special task, then you need to avoid having some infinte recursion if you try and calculate urgency for that special task)

Not sure if it complicates the alignment with TW, but seems like we should just adding some separate storage/ops for manging configuration - something like add a `app_config` table along with `ReplicaOp::SetConfigValue` and `ReplicaOp::ClearConfigValue`

**Comment by djmitche** [comment]
That's a good point -- I was thinking that adding new operations would be complicated, because we have to define their orderings with respect to the existing operations.  But, those orderings are trivial since they do not address the same data.  So, I'll close this and we can consider adding those ops when we eventually want to store config in the taskdb.
