### ISSUE TITLE
Support reading config from parent directories

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#79]
(from [#11](https://github.com/djmitche/taskchampion/issues/11#issuecomment-737247891))

Sort of like `git` will find a `.git` directory by going upward toward the fs root, let's look for `.taskchampion.yml` files up the directory hierarchy, and apply them in reverse order.

This will let folks apply defaults to specific subdirectories, e.g., if I'm in `~/my-novel` then the default report might just show tasks tagged with +novel.

**Comment by savchenko** [comment]
Isn't this contradictory to the design of TC? 

- Configs stored in `$XDG_CONFIG`
- Data is stored in `$XDG_DATA`

I don't quite see this working in a long-term if data backend can't be represented by file/folder structure.

**Comment by djmitche** [comment]
Yeah, that's a good point.  This shouldn't allow overriding the data directory, for example.  Maybe it only overrides certain config properties, like report definitions?

**Comment by savchenko** [comment]
Let's think about user story. Could you come-up with one and I will pick-up where you left tomorrow morning?

**Comment by djmitche** [comment]
@srfraser can you do so ^^?

**Comment by savchenko** [comment]
Any updates?.. Tagging TBD for now.

**Comment by srfraser** [comment]
I think this was a possible effect of my other request, but I don't have a good user story for this variant in particular.

**Comment by dbr** [comment]
The $PWD-based functionality sounds like it might be addressed by whatever comes out of https://github.com/taskchampion/taskchampion/discussions/163

**Comment by savchenko** [comment]
> I think this was a possible effect of my other request, but I don't have a good user story for this variant in particular.

How do you feel about what @dbr is proposing [here](https://github.com/taskchampion/taskchampion/discussions/163#discussioncomment-663011)?

**Comment by djmitche** [comment]
Let's keep this in #163 -- it's still at the "idea" stage and not "issue"
