### ISSUE TITLE
Implement synthetic tags

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#80]
TaskWarrior has a bunch of synthetic tags like +WAITING and +PENDING.  We could do the same thing pretty easily.  They should be synthesized entirely within the replica, rather than stored in the task DB.

**Comment by savchenko** [comment]
Could you give a short lecture on how "synthetic" tag is different from a natural one? Presumably by being automatically created?..

**Comment by djmitche** [comment]
Yeah, taskwarrior calls them virtual tags (and we could use that name too) - https://taskwarrior.org/docs/tags.html

basically they have the UI of a tag, but are defined not by the user but as some derivative of other attributes of the task.  So you can't

```
task 123 modify +WAITING
```
but
```
task 123 modify wait:1d
```
will make the task appear in
```
task list +WAITING
```

The mistake (IMHO) that TW makes is that it stores this information as actual tags.  So for example until a `task gc`, a task that has a `wait` attribute in the past is still tagged +WAITING.

**Comment by savchenko** [comment]
That's... A bit convoluted. Shall think about it with the fresh head. @dbr , any thoughts?

**Comment by djmitche** [comment]
For the user, it becomes a quick shorthand -- a common one is `task +ACTIVE` to show all active tasks (started and not stopped/completed).

**Comment by savchenko** [comment]
Logically this looks like something that belongs to v0.5.0, together with #81, #82 and #83. Adding to the same milestone, can be adjusted later.

**Comment by tbabej** [comment]
> The mistake (IMHO) that TW makes is that it stores this information as actual tags. So for example until a task gc, a task that has a wait attribute in the past is still tagged +WAITING.

Just chiming in that this is actually not correct, taskwarrior's virtual tags are, well, completely virtual :)

```c++
bool Task::hasTag (const std::string& tag) const
{
...
    if (tag == "WAITING")   return get ("status") == "waiting";
...
}
```

**Comment by djmitche** [comment]
Ah, thanks!  I remember seeing the `WAITING` tag set when I expected it to have been cleared, but perhaps that was because the task hadn't been "unwaited" yet, which AIUI is a data modification.  In TC a task becomes not-waiting when its wait time is in the past, without a data modification.

Thanks for the correction.  It sounds like we're basically implementing this the same way, then :)

**Comment by djmitche** [comment]
Actually, now that I look again, no -- TW gets this wrong, per the above snippet.  Something must come along and notice that a task's "wait" datestamp is in the past, and set its status to "pending", before it will show up in +WAITING.  That appears to happen as part of gc -- at least, I usually have to run `task` to get my outdated waiting tasks to flip back to pending.
