### ISSUE TITLE
Implement waiting

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#83]
This is a `wait` property with a timestamp, before which the task doesn't show up in most list views.

TaskWarrior gets this a little bit wrong in that it stores a separate flag for whether a task is waiting, and only refreshes that tag on a `gc` operation.  So if your typical view of the tasks does not involve running `gc` (for example, I keep my task list in a tmux pane), then on the rare occasions that you run a gc operation, suddenly dozens of waiting tasks appear.  Anyway, let's not do that.  A `wait` property in the past should be treated identically to one that is not displayed, for purposes of filtering.

**Comment by savchenko** [comment]
Wouldn't it make sense to adjust report or a view options instead of adding the new property? Say `ta list --before 2m` will show all tasks ending before +2 months from now.

**Comment by djmitche** [comment]
What does "ending" mean in that sense?

The `wait` functionality is useful for pushing things out and having them automatically reappear at a designated time.  For example, I might ask for review on a document, and then `task 123 wait:2d` to give the reviewer two days, after which time the task will reappear for me and I'll poke the reviewer if they haven't responded.

**Comment by savchenko** [comment]
> What does "ending" mean in that sense?

End date. Or we can `ta list created --before 2m` to show tasks created within 2 months before now.

> The wait functionality is useful for pushing things out and having them automatically reappear at a designated time. 

I see your point, the case is totally valid, I just carefully inquire if that's the right place to implement it.

**Comment by djmitche** [comment]
I guess "end date" is the last time the task was stopped?  Or the time it was marked completed?  That's definitely a different case.  And similarly, the created date has a different meaning.  This is specifically about "I don't want to think about this task until ___", which is an important GTD concept.  And that ___ is a property of the task, not of the query.

**Comment by savchenko** [comment]
Added to v0.5.0 together with #81 and #82
