### ISSUE TITLE
Support annotations

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#89]
Put annotations in properties named `annotation.<timestamp>`, so that individual annotations can be added and removed in single operations.

Add `annotate` and `deannotate` commands,

**Comment by savchenko** [comment]
Is this still planned? I can see this in `task.rs`, but the purpose of it is still a little unclear:

```rust
#[derive(Debug, PartialEq)]
pub struct Annotation {
    pub entry: Timestamp,
    pub description: String,
}
```

**Comment by djmitche** [comment]
It's still planned, but not completed.

The use-case is
```
ta add make dentist appointment
...
ta 13 annotate -- "called and left message with answering service"
...
ta 13 annotate -- "answering service says to call M-W before 3pm"
```
etc. to build up a list of timestamped notes on a particular task.

**Comment by savchenko** [comment]
The use case is fabulous! Would you like to target it as a part of a certain milestone?

**Comment by dbr** [comment]
What about `ta note 123 Thing` instead of `annotate`? Less typing!
