### ISSUE TITLE
Implement UDAs

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#90]
UDAs are basically named, typed attributes that represent data added to tasks by other serivces.

**Comment by savchenko** [comment]
Could you please provide an example? Considering that TC is a single-user, multi-endpoint application by design, I would expect others to simply overwrite parameters based on who has made the last change.

**Comment by djmitche** [comment]
Yeah, https://bugwarrior.readthedocs.io/en/latest/ uses a lot of these.  For example, syncing github issues into TC would involve attributes like `github_owner`, `github_repo` and `github_issue`.

The implementation of the attributes themselves and their merging is pretty simple, yes.  I think the details here are in the Rust API for getting and setting them.  TaskWarrior also defines them in the config file, but I'm not sure why that's necessary -- maybe just to specify types and thus allow displaying them in reports?

**Comment by savchenko** [comment]
Added to v0.8.0
