### ISSUE TITLE
Import TaskWarrior task list

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#94]
To support transitioning from TW to TC, we'll want to be able to import the output of `task export`, at least capturing the basic set of tasks.  If that misses recurrences or some other not-very-comparable feature, that's probably OK.

**Comment by savchenko** [comment]
Tagging TBD, pending https://github.com/taskchampion/taskchampion/discussions/162.

**Comment by djmitche** [comment]
I'd find this useful just for my own manual testing, importing my taskwarrior task DB and checking that it shows up in all the right ways.

**Comment by djmitche** [comment]
I got a start on this in https://github.com/taskchampion/taskchampion/compare/main...djmitche:issue94.  Just needs tests.  It worked with my TW task list :)
