### ISSUE TITLE
Add cache-control headers to server

### ISSUE THREAD

**Issue by djmitche** [taskchampion/taskchampion#99]
I think `Cache-Control: no-store` is appropriate for all client data.

**Comment by savchenko** [comment]
...with `max-age=0` "just in case"?

**Comment by djmitche** [comment]
Doesn't hurt :)

**Comment by savchenko** [comment]
Possibly dependant on https://github.com/taskchampion/taskchampion/issues/175, as EteBase might handle TLS/HTTP spec.

**Comment by djmitche** [comment]
I got a start on this at https://github.com/taskchampion/taskchampion/pull/new/issue99 but I'll wait until #128 lands first.
